[package]
name = "x86-disasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# to use `phf` in `no_std` environments
phf = { version = "0.11", features = ["macros"] }
